export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
export const FETCH_NOTES = 'FETCH_NOTES';
export const FETCH_AUTH_TOKEN = 'FETCH_AUTH_TOKEN';

export const ADD_NEW_NOTE = "ADD_NEW_NOTE";
export const ADD_NEW_NOTE_SUCCESS = "ADD_NEW_NOTE_SUCCESS";
export const SELECT_NOTE = "SELECT_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE";
